refact st
BinDeeCode/airbnb-demo-frontend pull request #2
Opened 2017-11-08 22:05 UTC by SergProduction

Cicle blyat

2017-11-08 22:10 UTC, BinDeeCode commented on src/Experiences/index.js
> +import ExpCard from "./ExperiencesCard.js";
Это чооооо :?

2017-11-08 22:10 UTC, BinDeeCode commented on src/Experiences/index.js
> -        </div>
Удалил слишком много

2017-11-08 22:10 UTC, BinDeeCode reviewed
Мне нравится

2017-11-08 22:14 UTC, SergProduction commented on src/Experiences/index.js
> +import ExpCard from "./ExperiencesCard.js";
Хуй через плечо

2017-11-09 01:00 UTC, BinDeeCode requested changes
Все нормально. Буду пользоваться как шпаргалкой

2017-11-09 01:02 UTC, closed without merging