Finished basic layout
BinDeeCode/airbnb-demo-frontend pull request #3
Opened 2017-11-09 07:21 UTC by BinDeeCode

Женя посмотри пожалуйста. Знаю что есть ошибки и их много, просто хочу услышать совета от тебя. За что взяться в первую очередь.

2017-11-09 13:47 UTC, imevro requested changes

2017-11-09 13:47 UTC, evgenyrodionov commented on src/App.js
> +import Header from "./Header/Header.js";
перечитай второй урок, раздел про модули/импорты и `index.js`

2017-11-09 13:47 UTC, evgenyrodionov commented on src/App.js
> +import Homes from "./Homes/index.js";
собственно, `index.js` можно опустить

2017-11-09 13:47 UTC, evgenyrodionov commented on src/App.js
> +import Exp from "./Experiences/index";
`index` можно опустить

Exp плохой нейминг, особенно с учетом того, что выше Explore есть

2017-11-09 13:47 UTC, evgenyrodionov commented on src/App.js
> +import Future from "./Future";
Future? Не припомню в макете такого

2017-11-09 13:47 UTC, evgenyrodionov commented on src/Experiences/ExperiencesCard.js
> +const CardDiv = styled.div`
а зачем нам знать что это див? Что это даст?

2017-11-09 13:47 UTC, evgenyrodionov commented on src/Experiences/ExperiencesCard.js
> +import star from "../star.png";
все иконки должны быть в свг

2017-11-09 13:47 UTC, evgenyrodionov commented on src/Experiences/ExperiencesCard.js
> +import React from "react";
зачем префиксовать файл как ExperiencesCard, если мы уже в директории Experiences?

2017-11-09 13:47 UTC, evgenyrodionov commented on src/Experiences/ExperiencesCard.js
> +const DivRait = styled.div`margin-top: 7px;`;
Что такое rait?

2017-11-09 13:47 UTC, evgenyrodionov commented on src/Experiences/index.js
> +const SeeAllButt = styled.div`
BUTT?

2017-11-09 13:47 UTC, evgenyrodionov commented on src/Experiences/index.js
> +const SeeAllButt = styled.div`
и почему ссылка сделана дивом, а не ссылкой? и судя по названию вообще подразумевалась кнопка

2017-11-09 13:47 UTC, evgenyrodionov commented on src/Experiences/index.js
> +const AsideBut = styled.aside`
зачем ты вообще в названия компонентов пихаешь хтмл-теги? в чем смысл?

2017-11-09 13:47 UTC, evgenyrodionov commented on src/Experiences/index.js
> +  left: 1090px;
зачем? у тебя уже есть райт, ты можешь ему поставить отрицательное значение чтобы сдвинуть правее контейнера

2017-11-09 13:47 UTC, evgenyrodionov commented on src/Experiences/index.js
> +  top: 285px;
научись двигать элемент на середину вертикали

2017-11-09 13:47 UTC, evgenyrodionov commented on src/Experiences/index.js
> +      <RelWrap className="row">
не смешивай свои стили и стили сетки — ломаешь предсказуемость

2017-11-09 13:47 UTC, evgenyrodionov commented on src/Experiences/index.js
> +const dataCard = [
Не проще `cards`?

2017-11-09 13:47 UTC, evgenyrodionov commented on src/Experiences/index.js
> +    price: "29",
почему строкой, а не числом?

2017-11-09 13:47 UTC, evgenyrodionov commented on src/ExploreAirbnb/ExploreAirbnb.css
> +.card > img {
если у тебя СК, откуда это взялось вообще? кстати, плохой селектор

2017-11-09 13:47 UTC, evgenyrodionov commented on src/ExploreAirbnb/ExploreAirbnb.css
> +  float: left;
забудь про флоаты, есть флексбоксы

2017-11-09 13:47 UTC, evgenyrodionov commented on src/ExploreAirbnb/ExploreAirbnb.css
> +  font-family: Circular Air Bold, Arial, Helvetica, sans-serif;
шрифты с несколькими словами берутся в кавычки

2017-11-09 13:47 UTC, evgenyrodionov commented on src/Footer/data.js
> +export const dataAirbnb = [
декларативность проще, чем джсон-конфигурация, поэтому просто размести ссылки через `<a href="">text</a>`

2017-11-09 13:47 UTC, evgenyrodionov commented on src/Footer/index.js
> +import logo from "./img/Shape.svg";
почему файл называется SHAPE?

2017-11-09 13:47 UTC, evgenyrodionov commented on src/Footer/index.js
> +import facebook from "./img/facebook.svg";
зачем файлы в директории img?

2017-11-09 13:47 UTC, evgenyrodionov commented on src/Footer/index.js
> +import "../gridstyle.css";
в вебпаке достаточно один раз импортнуть

2017-11-09 13:47 UTC, evgenyrodionov commented on src/Header/Header.js
> +                <li className="liStyle">
зачем тут список? и почему классы?

2017-11-09 16:24 UTC, BinDeeCode commented on src/Experiences/index.js
> +  left: 1090px;
Ты говорил что отрицательные значения зло. Или это только margin касается ?

2017-11-09 16:27 UTC, BinDeeCode commented on src/Header/Header.js
> +                <li className="liStyle">
В начале не знал как юзать СК. Сверстал это. Потом ты рассказал подробно про СК. Переделать все на СК ?

2017-11-09 16:27 UTC, BinDeeCode commented on src/Footer/index.js
> +import facebook from "./img/facebook.svg";
Чтоб хранить в одном месте картинки. Или так не делают ?

2017-11-11 20:10 UTC, evgenyrodionov commented
Не вижу исправления замечаний — не проверяю

2017-11-12 14:03 UTC, imevro requested changes

2017-11-12 14:03 UTC, evgenyrodionov commented on src/Cityes/index.js
> +  left: calc(89% + 68px);
right

2017-11-12 14:03 UTC, evgenyrodionov commented on src/Cityes/index.js
> +const Aside = styled.div`
это кнопка

2017-11-12 14:03 UTC, evgenyrodionov commented on src/App.js
> +import Cityes from "./Cityes";
Cities же

2017-11-12 14:03 UTC, evgenyrodionov commented on src/Experiences/index.js
> +  font-siz: e 32px;
wtf

2017-11-12 14:03 UTC, evgenyrodionov commented on src/Experiences/index.js
> +  left: calc(92% + 40px);
right проще будет

2017-11-12 14:03 UTC, evgenyrodionov commented on src/Experiences/index.js
> +  bottom: 213px;
top проще будет

2017-11-12 14:03 UTC, evgenyrodionov commented on src/Explore/Card.js
> +const Card = styled.div`
это же ссылки

2017-11-12 14:03 UTC, evgenyrodionov commented on src/Explore/Card.js
> +  @media (max-width: 576px) {
через min-width

2017-11-12 14:03 UTC, evgenyrodionov commented on src/Footer/index.js
> +      <ContainerFooter className="container">
ты и так в футере, нет нужды постфиксовать как Footer

2017-11-12 14:03 UTC, evgenyrodionov commented on src/Footer/index.js
> +                </Div>
зачем этот див? зачем вообще компонент называть по тегу?

2017-11-12 14:03 UTC, evgenyrodionov commented on src/Footer/index.js
> +                  <Text href="#">About us</Text>
это ссылка

2017-11-12 14:03 UTC, evgenyrodionov commented on src/Footer/styled.js
> +import arrowBot from "./arrowBot.svg";
bot?

2017-11-12 14:03 UTC, evgenyrodionov commented on src/Footer/styled.js
> +  @media (max-width: 576px) {
через min-width — прочитай 7 урок

2017-11-12 14:03 UTC, evgenyrodionov commented on src/Header/style.js
> +export const Links = styled.a`
линк мб, не линкс?

2017-11-12 14:03 UTC, evgenyrodionov commented on src/Popular/index.js
> +const dataPopularCard = [
поч не просто cards?

2017-11-12 14:03 UTC, evgenyrodionov commented on src/Popular/index.js
> +    price: "60",
числом

2017-11-12 14:06 UTC, merged

2017-11-12 15:13 UTC, BinDeeCode commented on src/App.js
> +import Cityes from "./Cityes";
Готово

2017-11-12 15:20 UTC, BinDeeCode commented on src/Cityes/index.js
> +const Aside = styled.div`
Готово

2017-11-12 15:25 UTC, BinDeeCode commented on src/Experiences/index.js
> +  font-siz: e 32px;
Готово

2017-11-12 15:34 UTC, BinDeeCode commented on src/Explore/Card.js
> +  @media (max-width: 576px) {
Это для мобильной версии. По другому не работает же.

2017-11-12 16:04 UTC, BinDeeCode commented on src/Cityes/index.js
> +  left: calc(89% + 68px);
Готово

2017-11-12 16:04 UTC, BinDeeCode commented on src/Experiences/index.js
> +  bottom: 213px;
Готово

2017-11-12 16:04 UTC, BinDeeCode commented on src/Experiences/index.js
> +  left: calc(92% + 40px);
Готово

2017-11-12 16:04 UTC, BinDeeCode commented on src/Explore/Card.js
> +const Card = styled.div`
Готово

2017-11-12 16:04 UTC, BinDeeCode commented on src/Footer/index.js
> +      <ContainerFooter className="container">
Готово

2017-11-12 16:04 UTC, BinDeeCode commented on src/Footer/index.js
> +                  <Text href="#">About us</Text>
Готово

2017-11-12 16:05 UTC, BinDeeCode commented on src/Footer/index.js
> +                </Div>
Готово

2017-11-12 16:05 UTC, BinDeeCode commented on src/Footer/styled.js
> +import arrowBot from "./arrowBot.svg";
Исправил

2017-11-12 16:05 UTC, BinDeeCode commented on src/Header/style.js
> +export const Links = styled.a`
Исправил

2017-11-12 16:05 UTC, BinDeeCode commented on src/Popular/index.js
> +const dataPopularCard = [
Исправил

2017-11-12 16:05 UTC, BinDeeCode commented on src/Popular/index.js
> +    price: "60",
Исправил

2017-11-13 08:51 UTC, BinDeeCode commented
open